spring:
  client:
    serviceUrl:
      defaultZone: http://localhost:6001/eureka/
  cloud:
    gateway:
      routes:
        - id: GestionCours
          uri: lb://GestionCours
          predicates:
          - Path=/cours/**
          - After=2024-01-20T17:47:47.789-07:00[Africa/Tunis]
          - Header=API-Key
          - Host=*.saslab.com.tn
          - RemoteAddr=192.168.1.1/24
          filters:
          - RewritePath=/utilisateur/(?<path>.*), /$\{path}
        - id: GestionFormateurs
          uri: lb://GestionFormateurs
          predicates:
          - Path=/Formateur/**
          filters:
          - RewritePath=/projet/(?<path>.*), /$\{path}    
